SYSFLAGS = -DRTP_LITTLE_ENDIAN=1
HSEARCH_LIB = $(OBJ_DIR)/libhsearch.a

# Because this gets included before 'all', let this be the first target in
# the file
truetarget: all

$(OBJ_DIR)/libhsearch.a: $(OBJ_DIR)/hsearch.o $(OBJ_DIR)/hsearch_r.o
	$(AR) rv $@ $?
	$(RANLIB) $@

$(OBJ_DIR)/hsearch.o: $(ARCH)/hsearch.c
	$(CC) -c $(CFLAGS) $? -o $@

$(OBJ_DIR)/hsearch_r.o: $(ARCH)/hsearch_r.c
	$(CC) -c $(CFLAGS) $? -o $@
