#!/bin/sh

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

USAGE="usage: multidump [-F format] [-t minutes] [-x bytes] filebase [addr]/port [...]"

args=""  # The flags to pass to each rtpdump
pids=""  # The list process IDs of the rtpdump processes
count=1  # The count of rtpdump sessions.

# Catch signals that need to be passed down to rtpdump.
trap 'kill -1  $pids' 1   # SIGHUP
trap 'kill -2  $pids' 2   # SIGINT
trap 'kill -15 $pids' 15  # SIGTERM

# Parse the flags.  Using getopt is the easiest way to tell where the
# options start.
while getopts 't:F:x:' c
do
    case $c in
    t | F | x)      args="${args} -$c ${OPTARG}";;
    \?)     echo $USAGE
	    exit 2;;
    esac
done
shift `expr $OPTIND - 1`

# Make sure we have a filebase, and get it.
if expr $# \< 1 > /dev/null
then
    echo $USAGE
    exit 2;
fi
filebase=$1
shift

# Get each of the destination addresses, and start an rtpdump for it.
# Its output goes to filebase.count.
while expr $# \> 0 > /dev/null
do
    echo "rtpdump $args $1 > $filebase.$count &"
    rtpdump $args $1 > $filebase.$count &
    pids="$pids $!"
    count=`expr $count + 1`
    shift
done

# Wait for all the processes to finish, if we used the -t option.
# If we didn't, rtpdump will never exit; our process exit will be handled
# by the traps above.
wait $pids
