.\" (c) 1998-2017 by Columbia University; all rights reserved
.\" (c) 2017 Jan Stary <hans@stare.cz>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd November 23, 2017
.Dt RTPPLAY 1
.Os
.Sh NAME
.Nm rtpplay
.Nd play back RTP sessions recorded by rtpdump
.Sh SYNOPSIS
.Nm
.Op Fl hTv
.Op Fl b Ar time
.Op Fl e Ar time
.Op Fl f Ar infile
.Op Fl p Ar profile
.Op Fl s Ar port
.Ar address Ns / Ns Ar port Ns Op / Ns Ar ttl
.Sh DESCRIPTION
.Nm
reads RTP session data recorded by
.Dq rtpdump -F dump ,
from standard input and resends the traffic to the given
.Ar address Ns / Ns Ar port ,
optionally with a time-to-live value of
.Ar ttl .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl b Ar time
Skip the first
.Ar time
seconds of input.
.It Fl e Ar time
Only use the first
.Ar time
seconds of input.
.It Fl f Ar infile
Read input from the given
.Ar infile
instead of from standard input.
.It Fl h
Print a short usage summary and exit.
.It Fl p Ar profile
Use the specified
.Ar profile
of payload type to frequency mapping.
By default,
.Nm
uses the frequency profile specified in RFC 1890.
For example, A-law PCM audio will be a single channel
with a sample rate of 8 kHz.
The
.Ar profile
file consists of lines containing two numeric values:
the numeric payload type and the sample rate.
This is silently ignored if
.Fl T
is used.
.It Fl s Ar port
Send packets from the specified
.Ar port .
By default, packets are sent from a random port.
.It Fl T
Time the outgoing RTP packets according to the original arrival time.
By default, the RTP timestamps are used for timing instead.
This smooths jitter and restores the packet sequence.
RTCP packets are always sent with their original arrival timing,
which may change the relative order of RTP and RTCP packets.
.It Fl v
Print the packets to standard output as they are sent out.
By default,
.Nm
operates silently.
.El
.Sh SEE ALSO
.Xr rtpdump 1 ,
.Xr rtpsend 1
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Henning Schulzrinne Aq Mt hgs@cs.columbia.edu ,
with enhancements by
.An Ping Pan
and
.An Akira Tsukamoto Aq Mt akira.tsukamoto@gmail.com .
